services:

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    env_file:
      - .env
    ports:
      - 443:443
    secrets:
      - cert
      - key
    volumes:
      - type: bind
        source: ~/data/wordpress
        target: /var/www/wordpress
      - type: bind
        source: ~/data/site
        target: /var/www/html
      - type: bind
        source: ~/data/adminer
        target: /var/www/adminer
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    env_file:
      - .env
    volumes:
      - type: bind
        source: ~/data/wordpress
        target: /var/www/wordpress
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    env_file:
      - .env
    volumes:
      - type: bind
        source: ~/data/mysql
        target: /var/lib/mysql
    networks:
      - inception
    restart: always

  redis:
    container_name: redis
    build:
      context: requirements/redis
    env_file:
      - .env
    networks:
      - inception
    restart: always
  
  ftp:
    container_name: ftp
    build:
      context: requirements/ftp
    env_file:
      - .env
    ports:
      - 20:20
      - 21:21
      - 10090-10100:10090-10100
    volumes:
      - type: bind
        source: ~/data/wordpress
        target: /var/www/wordpress
    restart: always

  minecraft:
    container_name: minecraft
    build:
      context: requirements/minecraft
    env_file:
      - .env
    ports:
      - 25565:25565
    volumes:
      - type: bind
        source: ~/data/minecraft
        target: /minecraft/world
    restart: always

  site:
    container_name: site
    build:
      context: requirements/site
    env_file:
      - .env
    volumes:
      - type: bind
        source: ~/data/site
        target: /var/www/html

  adminer:
    container_name: adminer
    build:
      context: requirements/adminer
    env_file:
      - .env
    volumes:
      - type: bind
        source: ~/data/adminer
        target: /var/www/adminer
    networks:
      - inception
    

networks:
  inception:
    driver: bridge

volumes:
  site:

secrets:
  cert:
    file: ./requirements/secrets/ggalon.42.fr.crt
  key:
    file: ./requirements/secrets/ggalon.42.fr.key
