services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    env_file:
      - .env
    ports:
      - 443:443
    secrets:
      - cert
      - key
    volumes:
      - type: bind
        source: ~/data/wordpress
        target: /var/www/wordpress
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    env_file:
      - .env
    volumes:
      - type: bind
        source: ~/data/wordpress
        target: /var/www/wordpress
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    env_file:
      - .env
    volumes:
      - type: bind
        source: ~/data/mysql
        target: /var/lib/mysql
    networks:
      - inception
    restart: always

  redis:
    container_name: redis
    build:
      context: requirements/redis
    env_file:
      - .env
    networks:
      - inception
    restart: always
  
  ftp:
    container_name: ftp
    build:
      context: requirements/ftp
    env_file:
      - .env
    ports:
      - 20:20
      - 21:21
      - 10090-10100:10090-10100
    volumes:
      - type: bind
        source: ~/data/wordpress
        target: /var/www/wordpress
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge

secrets:
  cert:
    file: ./requirements/secrets/ggalon.42.fr.crt
  key:
    file: ./requirements/secrets/ggalon.42.fr.key
