services:
  nginx:
      container_name: nginx
      build:
        context: ./nginx
      ports:
        - 443:443
      volumes:
        - ./nginx/html:/usr/share/nginx/html
        - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/ssl:/etc/nginx/ssl
      restart: always