services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    env_file:
      - ./nginx/.env
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress
    env_file:
      - ./wordpress/.env
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
    # mariadb:
    #   container_name: mariadb
    #   build:
    #     context: ./mariadb
    #   env_file:
    #     - ./mariadb/.env
    #   ports:
    #     - 3306:3306
    #   networks:
    #     - inception
    #   restart: always

volumes:
  wordpress:

networks:
  inception:
    driver: bridge